### PR TITLE
User installation

### PR DESCRIPTION
**Pull request by JulianT2013**
Minor typo corrections

### CODE REVIEW

**Comment by blueliquiddesigns** [comment]
Can you rebase your changes onto the upstream master, squash them and then push them to your fork?

This can be done by:

1. https://help.github.com/articles/configuring-a-remote-for-a-fork/
2. https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history
3. Push it to your fork.

Git Extension supports rebasing through the interface (just checkout your latest version and then rebase onto the upstream master). However, I believe you'll need to use the command line (use the little Git Bash icon in the tool bar) to do the squash – learning the common Git commands will be good for you anyway.

**Comment by blueliquiddesigns** [comment]
There are a few corrections that need to be made before we merge this in:

1. The `sed.exe.stackdump` file should be removed from the PR.
1. In user-setup-pdf.md we don't need to use ordered numbering. Markdown does this for us. To keep it easier to reorder the list at will we want to leave all the numbering set to `1.`

Fix those up, make sure to squash your changes into a single commit and update your fork.

**Comment by blueliquiddesigns** [comment]
The use of "alternative" instead of "alternate" is unfounded. See http://grammarist.com/usage/alternate-alternative/ for the correct usage of the words. 

Since all the references to "alternative" that you update are used in the context of something that serves in place of another "alternate" would be the preferred vernacular. 

It might be better to come up with a completely different word instead. I'll have a think on it.

**Comment by blueliquiddesigns** [comment]
This new line `Due to the increase in fonts used the total zip size is 25MB` may be better off as `Due to the increase in fonts included the total zip size is 25MB`. Thoughts?

**Comment by JulianT2013** [comment]
Alternate/alternative is a little confusing still. I didn't have time to look at it properly yesterday but, having slept on it, I've had some further thoughts. As far as I understand, [alternate](http://dictionary.reference.com/browse/alternate) means switching from one to another, or constituting an alternative, eg. *an alternate route*.

 "Alternatively" is correct, as in 
>*Alternatively*, the Gravity PDF team offers design and integration services for those looking for a custom solution..."

ie. You can do it yourself or, alternatively we can do it for you.

But, in this case:
>When enabled you can add an alternative header to the first page of your PDF document.

Perhaps "different" is a better word to use. :)
> When enabled you can add a *different* header to the first page of your PDF document.

**Comment by blueliquiddesigns** [comment]
Looks like you hit the nail on the head regarding when to use alternate / alternatively. I think `different` should work when talking about the headers/footers. But we'll leave `alternate` in the `gfpdf_post_pdf_save` section.

**Comment by JulianT2013** [comment]
I've often seen people (mostly Americans) use "alternate" when they probably mean "alternative".
At any rate we should limit repeating words like these, for clarity's sake.

On the whole, though, the documentation reads pretty clearly. Not overly technical. :)

**Comment by blueliquiddesigns** [comment]
Let's review this in more detail next week.

**Pull request merged**
